### ISSUE TITLE
Use RxMobius.subtypeEffectHandler to handle effects

### ISSUE THREAD

**Issue by togi** [sgrekov/AndroidMobiusSample#3]
Basically it will allow you to write one ObservableTransformer per effect type.

So instead of using `when` to filter out `GetSavedUserEffect` you would implement an `ObservableTransformer<GetSavedUserEffect, LoginEvent>`, and register it like this:

```kotlin
  RxMobius.subtypeEffectHandler()
    .add(GetSavedUserEffect::class.java, handleGetSavedUserEffect) // inject your transformer here
    .build()
```

There are also some variants of `add` that you can use if you only want to do a `map`-style operation or if your effect doesn't emit any events (for example if it triggers an intent to navigate to a different page).

**Comment by sgrekov** [comment]
Done
