### ISSUE TITLE
org.eclipse.mylyn.github:org.eclipse.egit.github.core is causing a problem

### ISSUE THREAD

**Issue by lgtout** [sgrekov/AndroidMobiusSample#4]
https://github.com/sgrekov/AndroidMobiusSample/blob/2343dfbd7fca2e5b7c2b9a86cbaeec0f996df97b/app/build.gradle#L41

This line of `build.gradle` is causing a problem in Android Studio:
`ERROR: Failed to resolve: org.eclipse.mylyn.github:org.eclipse.egit.github.core:4.8.0.201706111038-r`

Any suggestions on how to resolve this? 

Thanks!

**Comment by sgrekov** [comment]
Hi! 
Are sure about that?  It builds on my machine, and the artifact seems like still there
https://mvnrepository.com/artifact/org.eclipse.mylyn.github/org.eclipse.egit.github.core/4.8.0.201706111038-r

**Comment by lgtout** [comment]
Thanks @sgrekov.  I removed it from my .m2 directory and reimported the project and now all's fine.
